### ISSUE TITLE
Line Functionalities

### ISSUE THREAD

**Issue by gfry99** [mucsci-students/2022sp-420-NotJava#140]
A lot of stuff that can be done within a line can eventually be turned into methods for ease-of-use.  This could also be rolled into the line manager class that we are talking about implementing in a future sprint.

**Comment by dmforeacre** [comment]
Single functions inside of MainWindow.axml.cs have been created to handle getting classes by name and getting a relationship line by source & destination class. First step of refactoring lines.

**Comment by Robunnin** [comment]
We should probably create a separate "line manager" class. It would hold a reference to a canvas, keep track of the depicted relationships, and have functions for things like redrawing lines, registering/ unregistering depicted relationships, etc... 

The task of keeping tabs on depicted classes (and getting references to drawn class boxes by name) should probably be delegated to a "classbox manager" class that specializes in those functionalities. 

These are just some thoughts, but it might be better than filling up MainWindow with a whole bunch of bookkeeping code.
