### ISSUE TITLE
SQLite - Prepare model

### ISSUE THREAD

**Issue by dmforeacre** [mucsci-students/2022sp-420-NotJava#184]
**NOTE: This feature has been dropped**

- [ ] Add Primary key attributes to Diagram, Class, Relationship, Method, etc... (check if SQLite-net allows multiple columns in PK, make a counter for PK if it does not)
 - [ ] Add relationship attributes in model classes (mostly will be one to many, for instance (one)Diagram -> Class(many))
 - [ ] Add foreign key constraints to classes on the "many" side of a relationship to relate the classes
 - [ ] Create a new implementation of IDiagramFile that stores the diagram in a SQLite file.
 
 - Primary: @Robunnin
 - Secondary: @gfry99
 - Size: 🟣Epic🟣
 - Actual Size: 
 - Actual Time:

**Comment by Robunnin** [comment]
**NOTE: We have decided to drop this feature because of the complexities surrounding it**
