### ISSUE TITLE
Session Saving / Loading - Implement

### ISSUE THREAD

**Issue by dmforeacre** [mucsci-students/2022sp-420-NotJava#185]
**NOTE: This feature has been dropped**

- [ ] On view load, try to load the active diagram from the SQLite state file. If it fails or does not exist, set the active diagram to a new, blank diagram.
 - [ ] In the binding for the event when a Diagram is changed, save the new Diagram state to the SQLite state file
 
 - Primary: @robunnin
 - Secondary: @gfry99
 - Size: 🔵Rare🔵
 - Actual Size: 
 - Actual Time:

**Comment by Robunnin** [comment]
**NOTE: We have decided to drop this feature because of the complexities surrounding it**
