### ISSUE TITLE
I thought we were validating names when we construct the object.  What is the benefit to validating the input through the OnClick event handler?

### ISSUE THREAD

**Issue by mayoung00** [mucsci-students/2022sp-420-NotJava#20]
I thought we were validating names when we construct the object. What is the benefit to validating the input through the OnClick event handler? Having the validation inside of the button event handeler means we need to re-implement the validation somewhere else when we create the CLI interface

_Originally posted by @mayoung00 in https://github.com/mucsci-students/2022sp-420-NotJava/pull/18#r798181456_

**Comment by Robunnin** [comment]
@mayoung00 I believe we discussed the answer to this issue in class (although sadly I did not see it until now). If you are good with this question then you can resolve this issue.

**Comment by gfry99** [comment]
*Thumbs-up emojo*
