### ISSUE TITLE
New line bug introduced with newly scale-able classes

### ISSUE THREAD

**Issue by gfry99** [mucsci-students/2022sp-420-NotJava#203]
With the introduction of class boxes resizing to fit their contents, a new bug has presented itself where the lines being drawn to the resized class are clipping through it in a way that they shouldn't be.

**Comment by Robunnin** [comment]
![image](https://user-images.githubusercontent.com/89474048/160026757-28bced16-b943-4e79-9e91-45b60fe35351.png)

**Comment by willkill07** [comment]
Unsure if resolved, but here's another instance:
<img width="1103" alt="Screen Shot 2022-04-04 at 4 20 18 PM" src="https://user-images.githubusercontent.com/2007799/161625310-8d8d947b-b114-42cc-bae0-e9d5cb487e09.png">

**Comment by dmforeacre** [comment]
Has been resolved with #244
