### ISSUE TITLE
Export diagram as image (CLI, optional)

### ISSUE THREAD

**Issue by dmforeacre** [mucsci-students/2022sp-420-NotJava#236]
-- Custom renderer -- 
 - [ ] Should be able to write/ scale text to an image
 - [ ] Should be able to depict the class boxes (drawing rectangles). The rectangles start at their locations set in the file but should encompass all info that needs to be shown.
 - [ ] Program should not crash when using this in a headless mode (SSH)
 - [ ] Add an "export" command. Wire it in with tab completion. Should take a file path to export. Should display a success message when the export works. Should display an error message when the diagram is empty.
 
 - Primary: 
 - Secondary: 
 - Size: 🟠Legendary🟠
 - Actual Size: 
 - Actual Time:

**Comment by gfry99** [comment]
Dropping this feature as we don't really need the points and don't have time
