### ISSUE TITLE
Deleting class attribute

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022sp-420-NotJava#25]
- [x] Create some UI element that will be used to delete an attribute
- [x] Prompt user for Target Class and Target Attribute
- [x] On confirmation, delete class attribute
 
 - Primary: @gfry99
 - Secondary: @mayoung00
 - Size: 🟢Uncommon🟢
 - Actual Size: 🟢Uncommon🟢
 - Actual Time: ~90 minutes

**Comment by gfry99** [comment]
*Thumbs-up  Emoji*
