### ISSUE TITLE
Saving Diagram File

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022sp-420-NotJava#27]
- [x] Create a save button 
 - [x] Find a good way to serialize ("convert") the diagram to JSON
 - [x] File selection dialog
 
 - Primary: @robunnin
 - Secondary: @mayoung00
 - Size: 🟠Legendary🟠
 - Actual Size: 🔵Rare🔵
 - Actual Time: 30 minutes

**Comment by gfry99** [comment]
Change wording to let users know that a new file will be created within the path given if the file does not already exist.

**Comment by Robunnin** [comment]
Checks for user friendliness should probably happen during a refactoring pass. I will try to not forget to do this.

**Comment by Robunnin** [comment]
I have working prototype save/ load dialog boxes that I hope to be able to get in for sprint one. They should solve the user friendliness issues surrounding saving and loading.

**Comment by Robunnin** [comment]
Today we merged my file selection dialogs refactor. This feature is now fully finished for this sprint.
