### ISSUE TITLE
Load a diagram file

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022sp-420-NotJava#28]
- [x] Create a "Load Diagram" button
 - [x] Ensure button goes to file selection prompt
 - [x] Open file selection dialogue
 - [x] Check to ensure diagram is valid
 - [x] Display error message if diagram is invalid
 
 - Primary: @robunnin
 - Secondary: @dmforeacre
 - Size: 🟠Legendary🟠
 - Actual Size: 🔵Rare🔵
 - Actual Time: 30 minutes

**Comment by Robunnin** [comment]
Today we merged my file selection dialogs refactor. This feature is now fully finished for this sprint.
