### ISSUE TITLE
Add a Relationship

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022sp-420-NotJava#32]
- [x] Add an "add relationship" button
 - [x] Add a user prompt for source
 - [x] Add a user prompt for destination
 - [x] Add functionality to add relationship object.
 
 - Primary: @gfry99
 - Secondary: @robunnin
 - Size: 🔵Rare🔵
 - Actual Size: 🔵Rare🔵
 - Actual Time: (With documentation) 3 hours

**Comment by gfry99** [comment]
*Thumbs-up  Emoji*
