### ISSUE TITLE
Help Button

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022sp-420-NotJava#33]
- [x] Add Help Button
 - [x] Add functionality to print options in console
 
 - Primary: @gfry99
 - Secondary: @dmforeacre
 - Size: 🟢Uncommon🟢
 - Actual Size: 🟢Uncommon🟢
 - Actual Time: ~30 minutes + our 4 hours meeting

**Comment by gfry99** [comment]
*Thumbs-up  Emoji*
