### ISSUE TITLE
Exit Button

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022sp-420-NotJava#34]
- [x] Add Exit button
 - [x] Add functionality to exit program
 
 - Primary: @gfry99
 - Secondary: @robunnin
 - Size: ⚪Common⚪
 - Actual Size: ⚪Common⚪
 - Actual Time: ~5 minutes after learning C# & Avalonia lol

**Comment by gfry99** [comment]
*Thumbs-up  Emoji*
