### ISSUE TITLE
The JSON file containing the example Diagram should be included in the repo at some point

### ISSUE THREAD

**Issue by Robunnin** [mucsci-students/2022sp-420-NotJava#41]
Just making a note from something discussed in our meeting today, the JSON file I put on Discord that has the testing Diagram should be included in the repo at some point in time.

**Comment by dmforeacre** [comment]
Until then, I didn't re-write the testing class I had before but I did uncomment the test instance so I could use it.

**Comment by dmforeacre** [comment]
There is a sample .json file linked in the discord general chat that can be used for this.

**Comment by Robunnin** [comment]
I have merged in the pull request with Daniel's example diagram. For now it is in the root of the repo, so if you are running in rider when you open a load dialog you will have to navigate up a few folder levels.
