### ISSUE TITLE
Project does not compile after merging pull request #50

### ISSUE THREAD

**Issue by Robunnin** [mucsci-students/2022sp-420-NotJava#51]
@mayoung00 @dmforeacre @gfry99 @CeeJay-S 
The last thing to be merged into develop has code issues that are causing the project to not compile.

- **SourceClass** and **DestinationClass** in Relationship need to be made properties (readonly outside of Relationship, read/ write within). They currently have only private access within Relationship, but Diagram tries to access them
- In the DeleteRelationship method in Diagram, there is a method call to "RelationshipExists", but that method does not exist
- RelationshipNonexistentException is being used in Diagram and MainWindow.axaml.cs, but this exception has not been created yet

We need to make sure that before approving pull requests and merging code that we are testing the submitted code.

**Comment by Robunnin** [comment]
The changes associated with this pull request have since been rolled back. We are waiting for the changes to be made/ reviewed/ approved.

**Comment by dmforeacre** [comment]
After the rollback, the above issues have been addressed and a fixed branch was pushed onto develop.
