### ISSUE TITLE
(Graphical) Class Graphical Depiction Functionality

### ISSUE THREAD

**Issue by dmforeacre** [mucsci-students/2022sp-420-NotJava#92]
- [x] Programmatically create / add classes to the window. (And then fields and methods on the class).

- [x] Add functionality to controls (edit, rename delete, etc..) for classes, fields, methods within the class view
 
 - Primary: @Robunnin @gfry99
 - Secondary: @mayoung00

 - Size: 🟠Legendary🟠
 - Actual Size: 🟠Legendary🟠
 - Actual Time: > 10 Hours

**Comment by Robunnin** [comment]
With PR #133 this feature is in!
